### ISSUE TITLE
Add custom user agent column to list view

### ISSUE THREAD

**Issue by theofficialgman** [shlinkio/shlink-web-component#434] opened 2024-09-16 16:03 UTC
### Summary

Under the "Browser" (or another new configurable column). It would be nice to show the raw user agent sent instead of the hardcoded parsed list:
https://github.com/shlinkio/shlink-web-component/blob/c974790cabc1396ce7be744507142fd95bedeb52/src/visits/utils/index.ts#L7-L20

### Use case

In usecases where the user agent is customized by the sender (or simply not in the hardcoded list) it would be nice to view this information within the web interface.

We use shlink specifically for tracking install/uninstall/update's for applications in pi-apps (https://github.com/Botspot/pi-apps). We use the /track function exclusively (and have no need for shlink's redirects functionality) and have control over the user agent that gets sent client side. We would like to add some of our own custom information to the user agent (ie: hardware and operating system information). We can see this raw user agent information in the shlink cli (or by parsing the database directly) but it would be nice to have this also exposed via the web client. The Operating Systems and Browsers categories provide us no use because of the custom user agent so they just show "Other"

**Comment by acelaya** [comment] 2024-09-16 16:32
Yeah, I think there's a valid use case for this. Not sure if the browser chart is the right place, as that is more useful if there's some kind of grouping, bit u perhaps the visits table could have a rifle to either show the Browser and OS columns, or the raw user agent.

**Comment by theofficialgman** [comment] 2024-09-16 17:07
> Not sure if the browser chart is the right place, as that is more useful if there's some kind of grouping

The chart would be nice if automatic grouping could be performed based on just the user agent.
Just to provide out usecase, we currently us the user agent `Pi-Apps Raspberry Pi app store` and have the nginx server filter out anything else to prevent any unintended traffic. I want to basically extend that to include hardware/operating systems info which are client already has parsed from the host system

ex:
```
Pi-Apps Raspberry Pi app store; Raspberry Pi 5 Model B Rev 1.0; Debian GNU/Linux 12 (bookworm)

Pi-Apps Raspberry Pi app store; Xiaomi Mi Pad 5 Pro (CSOT); Armbian 24.8.2 noble

Pi-Apps Raspberry Pi app store; Orange Pi 5 Pro; Armbian 24.5.2 noble

Pi-Apps Raspberry Pi app store; Apple MacBook Air (M1, 2020); Ubuntu 24.04 LTS

Pi-Apps Raspberry Pi app store; Nintendo Switch (OLED model); Ubuntu 24.04.1 LTS
```

**Comment by theofficialgman** [comment] 2024-09-17 21:26
Just an FYI, we settled on the following format which can be extended as fit:
```
Raspberry Pi 400 Rev 1.0; bcm2711; 78c331be78aed33be478e6e07eb153510dfe1016; 29cdefbea8e21c23a927222cb9ccd9139ace8a3c; Debian 12; 64
```
which corresponds to
```
model name; SOC name; hash of machine-id; hash of serial-number; OS Name and Version; architecture
```

**Comment by acelaya** [comment] 2024-09-18 06:58
How exactly would you expect those user agents to be grouped in a chart? Because they seem like unique values, so you would end up with one segment per visitor, which defeats a bit the value of a chart.

How exactly would you benefit from a doughnut chart displaying that kind of information? For me it would be very hard to use effectively.

The Browsers chart is designed in a way that you see, from a high level perspective, the most used browsers from people visiting your link/s. A very convoluted chart would not be very useful for the average Shlink user.

**Comment by acelaya** [comment] 2024-09-18 18:36
Oh! But then you don't want to see the raw user agents (your original request), you actually want existing capabilities, in this case, the OS chart it seems, which is something already supported.

The problem is that you are providing non-standard user agents, which cannot be parsed following standard methods. That's why all visits with those user agents end up in "other".

You should make sure those clients are using standard user agent formats, and then everything should work out of the box.

Here you can see the format you should be following https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

And [bowser](https://www.npmjs.com/package/bowser) is the library used here to resolve browser names and operating systems from user agents, in case you want to test it.

The logic is pretty simple https://github.com/shlinkio/shlink-web-component/blob/main/src/visits/utils/index.ts#L22

**Comment by theofficialgman** [comment] 2024-09-18 19:27
> Oh! But then you don't want to see the raw user agents (your original request), you actually want existing capabilities, in this case, the OS chart it seems, which is something already supported.

Raw user agents would allow me to use the "search" tool that exists and search for particular matches. I would still prefer that be an option.

> The problem is that you are providing non-standard user agents, which cannot be parsed following standard methods. That's why all visits with those user agents end up in "other".

I'm well aware.

> You should make sure those clients are using standard user agent formats, and then everything should work out of the box.

Ha! LOL. There is no such thing as "standard user agent formats". Go read bowser source and that will be clear.

> Here you can see the format you should be following https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

See above, and not useful for my intentions.

> And [bowser](https://www.npmjs.com/package/bowser) is the library used here to resolve browser names and operating systems from user agents, in case you want to test it.

Yeah I already looked it over hours ago before my previous comment. It is unmaintained (for years) and not at all useful for this regard. Everything is hardcoded in bowser which is which it has 100s of open issues an fails to recognize any real version strings after its last update date (2020).

> The logic is pretty simple https://github.com/shlinkio/shlink-web-component/blob/main/src/visits/utils/index.ts#L22

I'm well aware but can't do much because of this https://github.com/shlinkio/shlink-web-client/discussions/1300

**Comment by acelaya** [comment] 2024-09-18 19:56
Ok, this is derailing and it's becoming harder for me to actually understand what's wanted or not. 

I don't like your tone either, so I'm closing this for now.

If you open another issue, showing the expected respect, with a concise and concrete request, which would be useful for the general user base and not just for you, I'll reconsider.

**Closed by acelaya** 2024-09-18 19:56 UTC
Labels: feature
